USE `cusmasydb`;

CREATE PROCEDURE `sp_Insert_Ort`(IN `_plz` INT, IN `_ort` VARCHAR(200))
	LANGUAGE SQL
	NOT DETERMINISTIC
	CONTAINS SQL
	SQL SECURITY DEFINER
	COMMENT ''
BEGIN
INSERT INTO Ort VALUES ('', _plz, _ort);
END;


CREATE PROCEDURE `sp_Insert_AnbieterTyp`(IN `_bezeichnung` VARCHAR(200))
	LANGUAGE SQL
	NOT DETERMINISTIC
	CONTAINS SQL
	SQL SECURITY DEFINER
	COMMENT ''
BEGIN
INSERT INTO AnbieterTyp VALUES ('', _bezeichnung);
END;
